server:
  port: 8090

spring:
#  配置rabbitmq
  rabbitmq:
    host: 192.168.56.129
    port: 5672
    username: rabbitadmin
    password: rabbitpwd
#   设置回调函数
#    confirm-type: 默认为None即不启用，correlated: , simple
#    correlated: 发布消息成功到交换机时触发回调方法
#    simple: 具有两个功能
#    1.与correlated相同
#    2.可以使用rabbittemplate调用waitforconfirm或waitForConfirmsOrDie
#     等待broker节点返回发送结果，根据结果来判定下一步逻辑
    publisher-confirm-type: correlated
    publisher-returns: true
