#端口设置
server:
  port: 8090

#数据源设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #设置编码和时区
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1234

   #jpa设置
  jpa:
    #显示sql语句
    show-sql: true
    #format sql 语句
    hibernate:
      naming:
        #驼峰匹配
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        #根据实体类自动更新表结构
      ddl-auto: update


